### ISSUE TITLE
add other controls to VyosSessionConfig package

### ISSUE THREAD

**Issue by mootezbessifi** [abessifi/pyatta#5]
some controls are needed and have to be added especially to teardown_config_session() method

**Comment by abessifi** [comment]
Could you please give an example how I can improve the code of teardown_config_session() by adding some other controls ?

**Comment by mootezbessifi** [comment]
For now, two enhancements may be considered:
1. You can add a little test before closing session that verify if you are in session or not.
2. Furthermore, you have to check if some modifications was gone through config session but it doesn't have been commited yet.

**Comment by abessifi** [comment]
checkout this revesion to see first enhancement suggestion :
https://github.com/vaytess/pyatta/tree/0bf01315c7ca2a9b3c3c1a23c6d1e6877a8b35b0
Note :
Checks of modifications in a config session before teardown have to be added in API side by calling session_changed() before teardown_config_session()
