### ISSUE TITLE
bug when returning multiple showCfg

### ISSUE THREAD

**Issue by mootezbessifi** [abessifi/pyatta#8]
when you try to execute show command line more than one time. In fuct, the according process will be failed because in the execution level the execmd() method changes the arguments content, thus, the next execution will rise an exception related to operation_name() method.

**Comment by abessifi** [comment]
Fix bug #8. List of command args is not overrided after performing execUtils()
https://github.com/vaytess/pyatta/commit/b4e39cdc04ef21882dbfe7e62002fb6e5c80c2ce
